utest failure: <lambda>
  arg 0=0
  arg 1=1
  arg x='x'
  arg y='y'
  expected value: True
  returned value: False

utest failure: raise_unexpected
  expected value: True
  raised exception: Exception('unexpected',)

utest failure: <lambda>
  expected exception: Exception('expected',)
  returned value: True

utest failure: raise_unexpected
  expected exception: Exception('expected',)
  raised exception: Exception('unexpected',)

utest failure: gen
  arg 0=[1]
  expected sequence: [1, 2]
  returned sequence: [1]

utest failure: <lambda>
  expected sequence: [1, 2]
  returned value: 1

utest failure: 'utest_val fail test'
  expected value: True
  returned value: False

